[fix] ./manage pyenv.install - die when pyenv build fails
ERROR: When pyenv build fails, the pyenv command runs into a recursion [1]:

    ....
    BUILDENV  BUILDENV  BUILDENV  BUILDENV  BUILDENV  BUILDENV  BUILDENV  ERROR: Cannot install idna==3.1 and requests[socks]==2.25.1 because these package versions have conflicting dependencies.
    BUILDENV  BUILDENV  BUILDENV  BUILDENV  BUILDENV  BUILDENV  BUILDENV
    BUILDENV  BUILDENV  BUILDENV  BUILDENV  BUILDENV  BUILDENV  BUILDENV  The conflict is caused by:

[1] https://github.com/return42/searx-next/pull/4#issuecomment-821999497

Signed-off-by: Markus Heiser <markus.heiser@darmarit.de>

diff --git a/manage b/manage
--- a/manage
+++ b/manage
@@ -355,12 +355,14 @@ pyenv.install() {
     if pyenv.install.OK > /dev/null; then
         return 0
     fi
+    pyenv
+    pyenv.OK || die 42 "error while build pyenv (${PY_ENV_BIN})"
+
     (   set -e
-        pyenv
-    	build_msg PYENV "[install] pip install -e 'searx${PY_SETUP_EXTRAS}'"
-    	"${PY_ENV_BIN}/python" -m pip install -e ".${PY_SETUP_EXTRAS}"
-        buildenv
-    ) || die 42 "error while build & install pyenv (${PY_ENV_BIN})"
+       build_msg PYENV "[install] pip install -e 'searx${PY_SETUP_EXTRAS}'"
+       "${PY_ENV_BIN}/python" -m pip install -e ".${PY_SETUP_EXTRAS}"
+       buildenv
+    ) || die 42 "error while pip install (${PY_ENV_BIN})"
 }
 
 pyenv.uninstall() {
